sudo: false
language: java
jdk:
- oraclejdk8
script: docker ps && docker run --name=hello  hello-world && docker ps -a && docker images -a && docker stop hello && docker rm -v hello &&  docker ps -a && docker images -a 
